### ISSUE TITLE
The Filename can not contain non ASCII characters

### ISSUE THREAD

**Issue by gmoises** [JayXon/Leanify#10]
The filenames can not contain ñ, á, é, í, ó, ú, ü, Etc.
The filenames can not start with -

**Comment by JayXon** [comment]
What operating system are you using?
Filename contains `ñ` works fine here.
For filenames that start with `-`, you should use something like `./-blabla` instead of `-blabla`

**Comment by gmoises** [comment]
I'm using Windows 10 (preview); I have made a script to temporary rename
the files before calling Leanify.

It worked nicely and saved a lot of disk storage for me.

Thank you

On Thu, Jan 1, 2015 at 6:10 PM, JayXon <notifications@github.com> wrote:

> What operating system are you using?
> Filename contains ñ works fine here.
> For filenames that start with -, you should use something like ./-blabla
> instead of -blabla
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JayXon/Leanify/issues/10#issuecomment-68503148>.
>



-- 
Gabriel Moises

**Comment by JayXon** [comment]
If you are using Leanify on a lot of files, is easier to just put them into a folder and call Leanify with the folder path. Filenames shouldn't be an issue this way.

**Comment by gmoises** [comment]
Great to know. It is much easier this way.

Thank you

On Thu, Jan 1, 2015 at 10:43 PM, JayXon <notifications@github.com> wrote:

> If you are using Leanify on a lot of files, is easier to just put them
> into a folder and call Leanify with the folder path. Filenames shouldn't be
> an issue this way.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JayXon/Leanify/issues/10#issuecomment-68508674>.
>



-- 
Gabriel Moises

**Comment by javiergutierrezchamorro** [comment]
Another option would be using its short 8:3 names.

**Comment by JayXon** [comment]
Closing this since there are no new reports in 5 years, feel free to reopen or create new issue if this still happens.
