### ISSUE TITLE
Leanify does not support UNC path

### ISSUE THREAD

**Issue by 236571208** [JayXon/Leanify#12]
It seems that Leanify does not support UNC path.

**Comment by JayXon** [comment]
Is this necessary? Why do you use UNC path?

**Comment by 236571208** [comment]
@JayXon Many smart routers provide SMB network storage.
Or is there any way to specify output folder or path?

**Comment by JayXon** [comment]
Okay, I did some tests, UNC path of a file in the local computer is supported.
If the UNC path is a SMB, do you need any authentication to access it? Do you only have read permission?

Specify output path is another issue, I could add this feature in the future.

**Comment by 236571208** [comment]
@JayXon There is not any authentication. And I have all read & write permissions.
And I did some tests in another SMB, it works fine.
But this problem occured when it comes to XIAOMI router's SMB.

**Comment by JayXon** [comment]
Well, then it seems that's not a problem of leanify.

**Comment by 236571208** [comment]
@JayXon Need more test. The last modified date updated, but the file content did not change.

**Comment by JayXon** [comment]
I'm closing this now, feel free to reopen it if you have more information.
