### ISSUE TITLE
base64 encoded images in HTML files

### ISSUE THREAD

**Issue by javiergutierrezchamorro** [JayXon/Leanify#14]
As suggested by Jaff at http://encode.ru/threads/2036-Leanify?p=43423&viewfull=1#post43423

Would you like to add a small hack to optimise htm/html/css etc web based files wich contains base64 encoded images?
 Detect base64 image, convert to binary file, optimise it, encode it back to base64 and replace original image in document. 
 It work with .png, .gif, .jpeg images. Thank you in advance!

 some usefull info: http://en.wikipedia.org/wiki/Data_URI_scheme

**Comment by JayXon** [comment]
Good idea, I'll implement it when I have time.

However, there's a little technical problem.
For now, some of the html file are recognized by Leanify as xml file. Should I write a html parser or just use current xml library? Or, maybe just search for `data:image/png;base64`?

**Comment by javiergutierrezchamorro** [comment]
Thanks for your reply JayXon.

I would say that detecting data:image/png;base64 and data:image/jpeg;base64 would be enough. No matter if they are serialized inside and HTML or an XML, optimizing the encoded base64 data will still make it compatible with both markups.

**Comment by Jaff2002** [comment]
Just search for "data:image/xxx;base64," (where xxx is gif, jpeg or png ** it might be with mixded, upper or lowercase) and the image will end with " ) or '
For this optimisation of images please add it's own option when Leanify is called to optimise images but not the entire html/css file (just for compatibility reasons). Thank you!

**Comment by JayXon** [comment]
Searching is the easiest way to implement it. The only concern is that if the file is not html/js/css, but it also has `data:image/png;base64` in it, we may corrupt the file.

**Comment by javiergutierrezchamorro** [comment]
To be honest I do not think that finding an ocurrence such as data:image/???;base64 would be probable in file types other than HTML, XHTML, or XML.

They can happen in server side scripts outputing HTML such as PHP, ASP.NET or JSP, but this will not corrupt the outputed HTML.

Anyway, agree making it an option so it can be disabled.

**Comment by JayXon** [comment]
Well, for example, html is embedded inside of some binary format which has a field of the length of the html.

If I can't find a way to make sure I don't corrupt the file, then I'll have to make the option disabled by default.

**Comment by javiergutierrezchamorro** [comment]
Sounds fair making this option disabled by default. Or maybe it can be enabled if detected file extension is known to be safe such as HTML, XML, or XHTML, and left it disabled for PHP, EXE (where HTML could be a resource), ...

**Comment by lorents17** [comment]
Good day!
I have long had the idea to do this project, where the system automatically searches for the image base64 files in HTML, CSS, XML / SVG and extracts them. The draft also easily integrate them into your files back. I think the right thing to do a separate project on this issue.
I have not found a project that could support such.

**Comment by Jaff2002** [comment]
For images inside binary files (e.g. EXE files) replacing original image with optimised + space padding (until you reach same size as original image data) is best option but first you need to detect in wich kind of filetype you do the optimisation (htm/html.js.xml or binary).

**Comment by JayXon** [comment]
I think I'll only enable this on file with known extension (html, htm, js, css, etc.).
Binary files won't be supported for this feature, even if I add space padding, it may still corrupt the file if it has checksum.

**Comment by Jaff2002** [comment]
Thank you!

**Comment by JayXon** [comment]
Please try out the latest nightly build.

**Comment by Jaff2002** [comment]
It works! Test file (css inside) https://ebooks.adelaide.edu.au/o/orwell/george/o79a/o79a.epub

**Comment by JayXon** [comment]
Cool, feel free to create another issue if there are bugs.

**Comment by TPS** [comment]
To clarify, did this implement optimizing supported embedded images inside SVGs (.svg images), or just in HTML/XML/&c files that have such in them?

**Comment by JayXon** [comment]
yes, images in SVG works too

https://github.com/JayXon/Leanify/blob/b5f2efccde6f57c4dfecc2006e75444621763fd4/formats/xml.cpp#L267-L275
