### ISSUE TITLE
ODT corruption

### ISSUE THREAD

**Issue by javiergutierrezchamorro** [JayXon/Leanify#15]
As reported on FileOptimizer discussion (http://sourceforge.net/p/nikkhokkho/discussion/fileoptimizer/thread/666f945a/#2f64)

Setup: Win7x86 with FileOptimizer v7.60.1252

Steps:

Optimize a large LibreOffice ODT (Open Text Document) file (tested on 898k and 130k files)

Open file 
Defect: 
http://i.imgur.com/wqV9QHP.png 

OpenOffice 4.1.1 had the same response. LibreOffice (v4.3.5.2 and v4.3.7.2) prompted me to repair it and it came back ok.

Tested both with 32 and 64-bit versions and operating systems.

File compression was excellent: 898k -> 751k (or 84%). This is remarkable because it's even better than a 7-zip "ultra"-level compression of the same file, which cut less than 1% off the file size.

**Comment by JayXon** [comment]
It seems the test file contains an entry with 0 file size, but still use deflate compression instead of store, which waste 2 byte.
I thought nobody would do something like this, but apparently I was wrong.

I'll push the fix once I tested it.

**Comment by javiergutierrezchamorro** [comment]
Thanks.

**Comment by javiergutierrezchamorro** [comment]
Confirmed it is solved: https://sourceforge.net/p/nikkhokkho/discussion/fileoptimizer/thread/666f945a/#69a3
