### ISSUE TITLE
clang cannot support "-fuse-ld=gold"

### ISSUE THREAD

**Issue by nuomi1** [JayXon/Leanify#23]
https://gist.github.com/nuomi1/1de7077fa1ca76125f1b
https://gist.github.com/anonymous/469034ba6df1be56dfc109d1871c6cc9

```
clang: error: invalid linker name in argument '-fuse-ld=gold'
make: *** [leanify] Error 1
```

**Comment by JayXon** [comment]
I don't use mac, but both linux and mac clang builds are passing here: https://travis-ci.org/JayXon/Leanify
Does it work if you remove this flag?

**Comment by nuomi1** [comment]
It works if I remove this flag.

`LDFLAGS     += -flto`

**Comment by JayXon** [comment]
I'll probably disable gold on mac for now.

BTW, I noticed that superenv is removing -O3, which will make leanify much slower, you probably want to keep O3.

**Comment by JayXon** [comment]
https://github.com/JayXon/Leanify/commit/b5b11d7479ae29b34b6d0dc624a1a4ec793e457b should fix it

**Comment by zetaerre** [comment]
Same issue on FreeBSD 11.0 p1.

pkg install gcc solve the issue to me.
