### ISSUE TITLE
Error process .apk files with err msg `EOCD not found!`

### ISSUE THREAD

**Issue by yyjdelete** [JayXon/Leanify#27]
Process the test file with `Leanify.exe -d 1 app-debug.apk`, and get the below msg and an broken .apk file.
```
Central directory header magic mismatch!
EOCD not found!
```
[app-debug.zip](https://github.com/JayXon/Leanify/files/568407/app-debug.zip)(rename to .apk or just process it)

Tested with nightly build 3a29d22e win64/32
v0.4.3 win stable also failed, but only output `EOCD not found!`

**Comment by yyjdelete** [comment]
[out.zip](https://github.com/JayXon/Leanify/files/569090/out.zip)
An newer test case with apksign, zipalign and comments.

**Comment by JayXon** [comment]
Yeah... Leanify currently does not support zip files with any data between chunks, should be a easy fix.

**Comment by JayXon** [comment]
There's another problem... I assumed the order of local file headers is the same as entries in central directory file header, which is true for all the zip files I've encountered until now...
According to Wikipedia: `The order of the file entries in the central directory need not coincide with the order of file entries in the archive.`
Oh well  ¯\\_(ツ)_/¯ I guess I'll have to rewrite the whole zip parsing logic.

**Comment by yyjdelete** [comment]
Upload a test code, but still some wrong.
https://github.com/JayXon/Leanify/compare/master...yyjdelete:patch-2

**Comment by JayXon** [comment]
Overall looked ok, but I don't get why do you need out_embed_off_, dwf is just a zip file with a pre-pended header magic, there should be no special handling in the Zip class.

**Comment by yyjdelete** [comment]
Offset(CD/local) in orig dwf file is calc with the whole file instead of just the zip part(like zip.sfx does), so offset of the output zip part must be added to the output offset. Or the output file can not be open by [some CAD viewer](http://cadsofttools.com/products/plugins-for-3d-party-programs/)(It's interesting that some CAD viewer and ziper can open both dwf with/without the offset).

**Comment by JayXon** [comment]
Interesting, sounds like Leanify should support reading both too, and always write the correct one.
I tried to look for DWF specification, the only one I found is an HTML in the DWF Toolkit, but it has no mention of the offset at all, and probably many others also assumed the offset does not include the header, so the CAD viewer had to support the incorrect one too.

**Comment by JayXon** [comment]
https://github.com/JayXon/Leanify/tree/zip_parsing
All files work fine now except wizzquiz.zip, which has an invalid EOCD and some other data after the actual ZIP file. Will have to add more logic there to find the correct EOCD.

**Comment by yyjdelete** [comment]
Seems `wizzquiz.zip` was only used by a test expected error, it should be ok to ignore it.
https://github.com/haf/DotNetZip.Semverd/commit/a66bc699f6face92f1b81c00dd4fd8b6e967c960

**Comment by JayXon** [comment]
But `unzip`, `7z`, windows explorer and master branch Leanify all can handle it correctly, so I should support it otherwise it would be a regression.
