### ISSUE TITLE
功能建议：多线程处理

### ISSUE THREAD

**Issue by coderstory** [JayXon/Leanify#44]
知乎上看到的 很不錯的小工具 给个赞！

###  1.不过能加个多线程功能么？
批量处理几百张图片有点慢。。。。
i7 8700的性能发挥不出来呀

### 2.还有相同的相机拍出来 都是8MB多点单张
有些压缩成1MB多点 而有些6MB多 差异有点大？
这张压缩成6MB的图片直接扔到windows自带的画图工具另存为jpg 可以压缩到2MB
继续将这张2MB的图片扔到tinypng处理变成400K 我不指望能直接上400K  但也不至于8MB只压缩到了6MB

例子：https://imgchr.com/i/PG5dld 
          链接: https://pan.baidu.com/s/16lpqdHM41Ku8qIzg_Xn9Xw 密码: 4kza
这是被Leanify压缩后的 默认没有备份功能 所以没原图了

### 3. 增加忽略错误功能
比如某个文件优化失败了可以跳过继续优化别的

Processing: D:\Data\Desktop\DCIM\100D5500\Leanify.exe
Open file error!
????????????????????????????????????????

### 4.报错有点皮！

**Comment by JayXon** [comment]
1. 见 #13 
2. 见楼上
3. 正常情况下不会报错的，你这个是因为Leanify本身正在运行所以不能被修改，建议把Leanify放到别的文件夹
4. 什么是“皮”？
