### ISSUE TITLE
How to make jpeg progressive?

### ISSUE THREAD

**Issue by b1rdex** [JayXon/Leanify#47]
I see it in source, but how it works with default settings? Is it applied for all files or not? How do I force it to be always used?

**Comment by JayXon** [comment]
The default is progressive, but if it does not decrease file size then we keep the original, or if it's a small file and baseline is better than progressive then we use baseline.
There isn't an option to force progressive because we always prefer whatever that gives smaller file size.

**Comment by b1rdex** [comment]
That's sad because progressive is always bigger AFAIK. I'm not too good in c++, can you please help me with patch to force progressive for files bigger that 10KB?

**Comment by JayXon** [comment]
Are you sure? I think progressive is usually smaller for large images, and baseline is usually smaller for small images, for websites I think using baseline for small images is totally fine.
If progressive is an absolute must for all images, then I would suggest to use mozjpeg and manually specify the options to force progressive.
