### ISSUE TITLE
Fuzzing: Specially crafted input file results in repeatable crash when compiled with ASAN under Ubuntu/GCC. Allows for limited, controlled OOB read.

### ISSUE THREAD

**Issue by AIVIIVIAL** [JayXon/Leanify#50]
I found Leanify while doing some research and decided to use Radamsa to test the robustness of the application. It appears pretty solid. I grabbed a ton of test files and then ran this simple loop to generate some more files; for i in $(ls); do cat $i | radamsa; done.

I did note a few things that were interesting, the most of which was a crash noted by ASAN from mutated files that proved hard to debug. I've done the test case reduction already down from several hundred bytes to the smallest byte string I could find that still induced the crash.

I did note that by modifying the length of the input file, the resulting address of the crash could be changed. Note that in the reproduction steps below, amongst the output shows the READ attempt at crash time. Another interesting crash I noted was a WRITE of 1024 bytes in another crash file.
//Cleaning up stack traces.

**Comment by JayXon** [comment]
Thanks for the report, I always wanted to do some fuzzing.
Could you upload a file that could reproduce the crash?
For symbol, by default the Makefile strips debug information, maybe try remove `-s` from Makefile and recompile?

**Comment by AIVIIVIAL** [comment]
Yep. If you compile it with ASAN it should*? give you a similar error and here are the file contents that make up the smallest crash file that I could make:

READ:
root@X:~# cat unknown_crash
?.W\T17014118

Just echo that string at the bottom starting with a ? to a file and that’s my smallest working crash.

**Comment by AIVIIVIAL** [comment]
Update: after removing the strip debug symbols from the Makefile, ASAN behaves MUCH more appropriately and I would even venture to say these are all false positives. I am lightly running AFL over the binary for a while, but feel free to close these issues as a false positive!

**Comment by AIVIIVIAL** [comment]
root@X:~/asanleanify# ./leanify /root/clones/id\:000003\,sig\:11\,src\:012690\,op\:flip32\,pos\:14 
Processing: /root/clones/id:000003,sig:11,src:012690,op:flip32,pos:14
=================================================================
==24324==ERROR: AddressSanitizer: unknown-crash on address 0x7f307799a000 at pc 0x7f30768cddf8 bp 0x7ffe225fe0c0 sp 0x7ffe225fd868
READ of size 4294967295 at 0x7f307799a000 thread T0
    #0 0x7f30768cddf7 in __asan_memmove (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x8cdf7)
    #1 0x4405f3 in Ico::Leanify(unsigned long) (/root/asanleanify/leanify+0x4405f3)
    #2 0x42c8a1 in LeanifyFile(void*, unsigned long, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (/root/asanleanify/leanify+0x42c8a1)
    #3 0x42d5a0 in ProcessFile(char const*, stat const*, int) [clone .part.26] (/root/asanleanify/leanify+0x42d5a0)
    #4 0x40603d in main (/root/asanleanify/leanify+0x40603d)
    #5 0x7f3075e0c82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #6 0x40a0e8 in _start (/root/asanleanify/leanify+0x40a0e8)

AddressSanitizer can not describe address in more detail (wild memory access suspected).
SUMMARY: AddressSanitizer: unknown-crash ??:0 __asan_memmove
Shadow bytes around the buggy address:
  0x0fe68ef2b3b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe68ef2b3c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe68ef2b3d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe68ef2b3e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe68ef2b3f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0fe68ef2b400:[fe]fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe
  0x0fe68ef2b410: fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe
  0x0fe68ef2b420: fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe
  0x0fe68ef2b430: fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe
  0x0fe68ef2b440: fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe
  0x0fe68ef2b450: fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
==24324==ABORTING

Attack file that allows for a 4.3 billion byte read attempt & segfault
root@X:~/clones# cat id\:000003\,sig\:11\,src\:012690\,op\:flip32\,pos\:14  | base64
AAABAAEAAAAAAAAAAAD/////CQAAAACA

**Comment by AIVIIVIAL** [comment]
The address of the read can be controlled by crafting the file so that chunk_length, memory location of p_read, and 0xFFFFFFFF are relatively close to the desired location. Unsure if the memory can be retrieved from the segfault. 

A non-specially crafted example of this is here, pasted in base64:

root@X:~/clones# cat id:000003,sig:11,src:012690,op:flip32,pos:14 | base64
AAABAAEAAAAAAAAAAAD/////CQAAAACA

**Comment by JayXon** [comment]
This particular issue with ico should be fixed now, let me know if you can find other crash.

**Comment by AIVIIVIAL** [comment]
Controllable size read/write issue fixed in new commit. Closing issue.
