### ISSUE TITLE
Problems found with your Leanify X86 code (possible malware)

### ISSUE THREAD

**Issue by Mechatherium** [JayXon/Leanify#60]
Very quickly:

I've been using Nikkhokkho's Fileoptimizer software for over a year, but I can't use his latest release because both my AV and VirusTotal found malware in it. Some of the files marked as infected were Leanify which he included in his program.

I brought this up with him on Sourceforge and he pretty much brushed me off.

> Thank you for your offer. Usually it is better to report the FP to AV vendors. Unfortunately according to my experience, Avast team is not very responsive. Reason is that Leanify is also opensource, which means that it is hard of being harmful

So I thought I'd download Leanify, both x86 and x64, stable and nightly builds from your page so I could test them for myself. My AV pronounced them clean. Virustotal's scanners reported some malware in the x86 builds. The 64-bit builds were clean. I uploaded screenshots of my findings on Virustotal.

Before I went back to Nikkhokkho on Sourceforge I thought I'd let you know about this. I think you and Nikkhokkho make very useful software and I want to keep using it.

Thanks,
Tony
 
![leanify_win32_malware](https://user-images.githubusercontent.com/63214762/78514214-de23f980-7775-11ea-9243-07c978146d1a.png)
![leanify_win32_nightly_malware](https://user-images.githubusercontent.com/63214762/78514208-d6645500-7775-11ea-8111-a96f2a2aa4c0.png)

**Comment by NGrPXL** [comment]
Same here with Windows 10 Security
![Capture](https://user-images.githubusercontent.com/61785551/78641614-c5b8f980-78b1-11ea-9f9e-6de2d48f293f.PNG)

**Comment by JayXon** [comment]
Thanks for the report, however I'm pretty sure this is a false positive, we compile everything from source code in this git repository, which anyone can look at, I don't think there are any malware hidden in the source code.

I'm going to close this since there's not much I can do about it, you could try to report this as a false positive in your antivirus software, but I don't know how do they deal with those reports.
