### ISSUE TITLE
May mention OpenRaster file type as supported

### ISSUE THREAD

**Issue by f2d** [JayXon/Leanify#61]
Hello,
OpenRaster file type is not mentioned, while OpenDocument is.

I tried Leanify with some ORA files and it seems to work without problems, if only taking quite some time compressing PNGs inside.
Keeps `mimetype` as stored, minifies XML and PNGs, does nothing to app-specific `*.dat`, as expected.
Shaves about 30-50% on some files saved in MyPaint and Drawpile.

I'd suggest to put it separately from OpenDocument.
Applications that understand them are mutually exclusive, if I'm not mistaken.

Maybe like this:
```
#### OpenDocument (.odt, .ods, .odp, .odb, .odg, .odf)

It is based on XML and ZIP.

#### OpenRaster (.ora)

It is based on OpenDocument and PNG.
```

**Comment by JayXon** [comment]
Thanks! This is the first time I've heard of OpenRaster, added to README.
