### ISSUE TITLE
Color of some pixels may be changed when alpha channel is 0 in PNG file.

### ISSUE THREAD

**Issue by Leoongithub** [JayXon/Leanify#68]
Although alpha channel is 0 means color is meaningless, is there an option to not change RGB channels' value?

**Comment by JayXon** [comment]
By default `lossy_transparent` option is enabled because there's no difference in the pixels we can see, it is possible to add an option to disable this, but I would like to know more about the use case, why do you need it to not change?

**Comment by Leoongithub** [comment]
I can use transparent area to record some hidden information.
How do I use this option  in CLI? Or I need modify the source code?

**Comment by JayXon** [comment]
Currently it's not exposed in CLI, but you can remove [this line](https://github.com/JayXon/Leanify/blob/master/formats/png.cpp#L111) in the code

**Comment by doterax** [comment]
Hi @javiergutierrezchamorro, I have found that you have updated leanify in https://sourceforge.net/p/nikkhokkho/code/1755/ 

So, please consider to handle additional parameter "--png-lossless-transparent" (Prohibit altering hidden colors of fully transparent pixels.) By default do not add anything, but user have to have ability to use it.
