### ISSUE TITLE
Recursive compression of images within epub files

### ISSUE THREAD

**Issue by TheGreatNi** [JayXon/Leanify#73]
Hi, I use Leanify to recompress epub files frequently, and I noticed it doesn't compress the image files inside the epub. For now, I've been extracting the epub files and compressing the images, then compressing it into an epub before optimizing that with Leanify.

It would be a lot simpler and more streamlined to have Leanify do this on it's own.

**Comment by JayXon** [comment]
This should work, unless `-f` is passed, if you aren't doing that, could you share an epub that could reproduce this issue?

**Comment by TheGreatNi** [comment]
I apologize, I was using leanify via another tool and it seems that tool just doesn't use leanify correctly. I'll be sure to use leanify on it's own from now on.

Again, sorry!

**Comment by JayXon** [comment]
maybe that tool is using `-d 1`?
