### ISSUE TITLE
Cflags issue on Apple M1 (ARM)

### ISSUE THREAD

**Issue by MoNTE48** [JayXon/Leanify#85]
"clang: error: argument unused during compilation: '-msse2' [-Werror,-Wunused-command-line-argument]"
"error: unknown FP unit 'sse'"

```
CFLAGS      += -Wall -Werror -O3 -msse2 -mfpmath=sse -flto
```

should be replaced on:

```
CFLAGS      += -Wall -Werror -O3 -flto
```

In any case, what are the benefits of the flags above when used with modern gcc/clang?

**Comment by JayXon** [comment]
yeah those flags should be removed now

**Comment by MoNTE48** [comment]
@JayXon, any updates on my issue? Only two (tested) lines.

**Comment by skhaz** [comment]
I have the same issue
