### ISSUE TITLE
[NOISSUE] Was there previously a GUI version called Leanify++?

### ISSUE THREAD

**Issue by RDKRACZ** [JayXon/Leanify#88]
This would be a better fit for Discussions but these are not enabled in this repo.
So, I was chatting with ChatGPT about image compression and it randomly mentioned that You also created Leanify++ which is a GUI for the command line version.
I wasn't able to find any info about this so is this an AI talking bullshit or something you experimented with and deleted?

<details>

![obraz](https://user-images.githubusercontent.com/43277609/212696216-dc3eb7e4-71ba-46a1-adae-f313ce6bad47.png)

</details>

**Comment by JayXon** [comment]
No, these large language models often make things up.
